src/Entity/Posts.php
<?php

namespace App\Entity;

use App\Repository\PostsRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PostsRepository::class)
 */
class Posts
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="posts")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="text")
     */
    private $text;

    /**
     * @ORM\Column(type="integer", options={"comment":"1=only_me, 2=friends, 3=public"})
     */
    private $privacy_id;
 
    /**
     * @ORM\Column(type="datetime", options={"default": "CURRENT_TIMESTAMP"})
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", options={"default": "CURRENT_TIMESTAMP"})
     */
    private $updated_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getText(): ?string
    {
        return $this->text;
    }

    public function setText(string $text): self
    {
        $this->text = $text;

        return $this;
    }

    public function getPrivacyId(): ?int
    {
        return $this->privacy_id;
    }

    public function setPrivacyId(int $privacy_id): self
    {
        $this->privacy_id = $privacy_id;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"username"}, message="There is already an account with this username")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $username;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $profile_pic;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $decoded_pass;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $cover_pic;

    /**
     * @ORM\OneToMany(targetEntity=Posts::class, mappedBy="user")
     */
    private $posts;

    /**
     * @ORM\OneToMany(targetEntity=FriendRequest::class, mappedBy="sender")
     */
    private $friendRequest;

    /**
     * @ORM\OneToMany(targetEntity=Messages::class, mappedBy="sender")
     */
    private $messages;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $about;

    public function __construct()
    {
        $this->posts = new ArrayCollection();
        $this->friendRequest = new ArrayCollection();
        $this->messages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getProfilePic(): ?string
    {
        return $this->profile_pic;
    }

    public function setProfilePic(?string $profile_pic): self
    {
        $this->profile_pic = $profile_pic;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getDecodedPass(): ?string
    {
        return $this->decoded_pass;
    }

    public function setDecodedPass(?string $decoded_pass): self
    {
        $this->decoded_pass = $decoded_pass;

        return $this;
    }

    public function getCoverPic(): ?string
    {
        return $this->cover_pic;
    }

    public function setCoverPic(?string $cover_pic): self
    {
        $this->cover_pic = $cover_pic;

        return $this;
    }

    /**
     * @return Collection|Posts[]
     */
    public function getPosts(): Collection
    {
        return $this->posts;
    }

    public function addPost(Posts $post): self
    {
        if (!$this->posts->contains($post)) {
            $this->posts[] = $post;
            $post->setUser($this);
        }

        return $this;
    }

    public function removePost(Posts $post): self
    {
        if ($this->posts->contains($post)) {
            $this->posts->removeElement($post);
            // set the owning side to null (unless already changed)
            if ($post->getUser() === $this) {
                $post->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|FriendRequest[]
     */
    public function getFriendRequest(): Collection
    {
        return $this->friendRequest;
    }


    public function addFriendRequest(FriendRequest $friendRequest): self
    {
        if (!$this->friendRequest->contains($friendRequest)) {
            $this->friendRequest[] = $friendRequest;
            $friendRequest->setSender($this);
        }

        return $this;
    }

    public function removeFriendRequest(FriendRequest $friendRequest): self
    {
        if ($this->friendRequest->contains($friendRequest)) {
            $this->friendRequest->removeElement($friendRequest);
            // set the owning side to null (unless already changed)
            if ($friendRequest->getSender() === $this) {
                $friendRequest->setSender(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Messages[]
     */
    public function getMessages(): Collection
    {
        return $this->messages;
    }

    public function addMessage(Messages $message): self
    {
        if (!$this->messages->contains($message)) {
            $this->messages[] = $message;
            $message->setSender($this);
        }

        return $this;
    }

    public function removeMessage(Messages $message): self
    {
        if ($this->messages->contains($message)) {
            $this->messages->removeElement($message);
            // set the owning side to null (unless already changed)
            if ($message->getSender() === $this) {
                $message->setSender(null);
            }
        }

        return $this;
    }

    public function getAbout(): ?string
    {
        return $this->about;
    }

    public function setAbout(?string $about): self
    {
        $this->about = $about;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\JsonResponse;
use App\Repository\UserRepository;
use App\Service\FileUploader;
use Symfony\Component\Security\Core\Security;
use App\Repository\PostsRepository;
use App\Repository\FriendRequestRepository;

class HomeController extends AbstractController
{
	private $fileUploader;
	private $UserRepository;
	private $security;
    private $postsRepository;
    private $friendRequestRepository;    


	public function __construct(FileUploader $fileUploader, UserRepository $UserRepository, Security $security,  PostsRepository $postsRepository, FriendRequestRepository $friendRequestRepository)
	{
		$this->fileUploader = $fileUploader;
		$this->UserRepository = $UserRepository;
		$this->security = $security;
        $this->postsRepository = $postsRepository;
        $this->friendRequestRepository = $friendRequestRepository;
	}

    public function index($id = null)
    {
        $logged = $this->security->getUser();
        if ($id) {
            $id = base64_decode($id);
            $user = $this->UserRepository->find($id);
            $isId = "yes";

            if ($logged->getId() == $id) {
                $isId = "no";
            }
        }else{
            $user = $logged;
            $isId = "no";
        }
        
        $user_id = $user->getId();
        $posts = [];
        
        if ($logged->getId() == $user->getId()){
            $posts = $this->postsRepository->myposts($user_id);
        }else{
            $wefrnd = "no";
            $ifFrnd = $this->friendRequestRepository->checkIfAlready($logged->getId(), $user_id);
            
            if ($ifFrnd) {
                $status = $ifFrnd->getStatus();
                if ($status == "accepted") {
                    $wefrnd = "yes";
                }
            }

            $posts = $this->postsRepository->getUserPosts($user_id, $wefrnd);
        }
        
        return $this->render('home/index.html.twig', [
            'posts' => $posts,
            'user' => $user,
            'isUrlHasId' => $isId
        ]);
    }

    /* update profile and cover photo */

    public function upload_pic(Request $request): JsonResponse
    {
    	$pic_type = $photo = $request->request->get('pic_value');
    	$photo = $request->files->get($pic_type);
    	$user = $this->security->getUser();
    	$user_id = $user->getId();

    	if ($pic_type == "cover_pic") {
    		$old_pic_name = $user->getCoverPic();    	
    	}

    	if ($pic_type == "profile_pic"){
    		$old_pic_name = $user->getProfilePic();
    	}

    	if ($photo) {

    		$return = $this->fileUploader->upload($photo, $pic_type);
    		
    		if ($return['status'] == "success"){
    		
    			$filename = $return['filename'];
    			if ($pic_type == "cover_pic") {
    				$update = $this->UserRepository->updateCoverImage($user_id, $filename);
	    			$saved_pic = $update->getCoverPic();
    			}

    			if ($pic_type == "profile_pic") {
	    			$update = $this->UserRepository->updateProfilePic($user_id, $filename);
	    			$saved_pic = $update->getProfilePic();
    			}

    			if($saved_pic == $filename){
    				if ($old_pic_name) {
    					$this->fileUploader->deleteOld($old_pic_name, $pic_type);
    				}
    			}
    			$return['image_path'] = "/images/".$pic_type."/".$filename;
    			$result = $return; 

    		}else{
    			$result['status'] = 'fail';
    			$result['error'] = "Something went wrong. Please try again";	
    		}
    	}else{
    		$result['status'] = 'fail';
    		$result['error'] = "Please select a image";
    	}

    	return new JsonResponse($result);
    }
}

templates/home/cover.html.twig
<div class="main cover_mobile">
	{% if user.id == app.user.id %}
	    <form method="post" enctype="multipart/form-data" action="{{ path('upload_pic')}}" id="cover_pic_form">
			<label for="cover_pic" class="cover_image_edit">
				<i class="fas fa-edit"></i> 
			</label>
			<input type="file" class="upload_pic_input" name="cover_pic" id="cover_pic">
			<input type="hidden" name="pic_value" value="cover_pic">
			<button type="submit" id="sbmt_cover_pic" style="display: none;"></button>
		</form>
	{% endif %}
	{% set url = path(app.request.attributes.get('_route'), app.request.attributes.get('_route_params')) %}

    <div class="cover">
    	{% if (user.coverPic) %}
        	<img src="{{ asset('/images/cover_pic/' ~ user.coverPic) }}" id="cover_pic_tag" />
    	{% else %}
        	<img src="{{ asset('/images/cover_pic/default_cover.jpg') }}" id="cover_pic_tag" />

    	{% endif %}

    	<ul class="below_cover">
		  	<li>
		  		{% if app.user.id != user.id %}  
		  			<a class="{% if '/about' in url %} active {% endif %}" href="{{ path('about', {id:user.id|base64_encode}) }}">About Info</a>
		  		{% else %}
		  			<a class="{% if '/about' in url %} active {% endif %}" href="{{ path('about') }}">About me</a>
		  		{% endif %}
		  	</li>

		  	{% if isUrlHasId == "no" %}
		  		<li>
		  			<a href="#home" data-toggle="modal" data-target="#myModal">Find friends</a>
		  		</li>
		  	{% endif %}

		  	<li>
		  		{% if app.user.id != user.id %}  
		  			<a class="{% if '/friends' in url %} active {% endif %}" href="{{ path('my_friend', {id:user.id|base64_encode}) }}">Friends</a>
		  		{% else %}
		  			<a class="{% if '/friends' in url %} active {% endif %}" href="{{ path('my_friend') }}">Friends</a>
		  		{% endif %}
	  		</li>

		  	
		  	{% if isUrlHasId == "no" %}
			  	<li>
			  		<a href="javascript:void(0);" data-toggle="modal" data-target="#postModal">Add post</a>
			  	</li>
			{% endif %}
			<li>
		  		{% if app.user.id != user.id %}  
			  		<a class="{% if '/profile' in url %} active {% endif %}" href="{{ path('home', {id:user.id|base64_encode}) }}">{{ user.name }}'s posts</a>
		  		{% else %}
			  		<a class="{% if '/profile' in url %} active {% endif %}" href="{{ path('home') }}">My posts</a>
		  		{% endif %}
	  		</li>
		  	
		  	<li>
		  		<a href="{{ path('post') }}">All posts</a>
		  	</li>

		  	{% if isUrlHasId == "no" %}
			  	<li>
			  		<a href="{{ path('user_account_update') }}">Account update</a>
			  	</li>
			{% endif %}
		</ul>
	    	
	    <div class="profile">
			{% if user.id == app.user.id %}
			    <form method="post" enctype="multipart/form-data" action="{{ path('upload_pic')}}" id="profile_pic_form">
					<label for="profile_pic" class="profile_image_edit">
						<i class="fas fa-edit"></i> 
					</label>
					<input type="file" name="profile_pic" id="profile_pic">
					<input type="hidden" name="pic_value" value="profile_pic">
					<button type="submit" id="sbmt_profile_pic" style="" le="display: none;"></button>
				</form>	
			{% endif %}
	        {% if (user.profilePic) %}
        		<img src="{{ asset('/images/profile_pic/' ~ user.profilePic) }}" id="profile_pic_tag"/>
	    	{% else %}
        		<img src="{{ asset('/images/profile_pic/fallback.jpg') }}" id="profile_pic_tag"/>
	    	{% endif %}

		    <span class="cover_username">
		    	{{ user.name }}
		    </span>
	    </div>
    </div>
</div>

templates/home/index.html.twig
{% extends 'website.html.twig' %}

{% block title %} ( {{ user.name }} ) {% endblock %}

{% block body %}

	{% include 'home/cover.html.twig' %}

	<div class="main">
		<div class="container">
	    	<div class="row">
		      	<div class="col-lg-8 post_list_div">
			      	{% for post in posts %}
				        <div class="post_list">
				        	<div class="post_header">
				        		{% if post.user.id == app.user.id %}
					        		<div class="dropdown right_side">
									  	<button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
									    	<i class="fas fa-ellipsis-v"> </i>
									  	</button>
									  	<ul class="dropdown-menu" aria-labelledby="dropdownMenu2">
									  		<li class="dropdown-item dropdown_link edit_post" hitUrl="{{ path('post_detail', {'id': post.id|base64_encode, 'type': 'model'}) }}">
									  			Edit 
									  		</li>
									  		<li class="dropdown-item dropdown_link del_post" hitUrl="{{ path('post_delete', {'id': post.id|base64_encode}) }}">Delete</li>
									  	</ul>
									</div>
								{% endif %}
					        	{% if app.user.profilePic %}
					        		<img src="{{ asset('/images/profile_pic/' ~ post.user.profilePic) }}" class="header_pro_pic">
					        	{% else %}
					        		<img src="{{ asset('/images/profile_pic/fallback.jpg')}}" class="header_pro_pic">
					        	{% endif %}
						        <span class="post_author">
						        	<a href="{{ path('home') ~ '/' ~ post.user.id|base64_encode}}" class="post_author"> {{ post.user.name }} </a>
						        </span>
						        <span class="post_time">
						        	<i class="fas fa-clock"> </i> {{ post.createdAt | date("M d, Y h:i A", "Asia/Calcutta") }}
					        	</span>
				        	</div>
				        	<span class="post_detail" id="post{{post.id}}">
			        			{{ post.text | raw }}
			        		</span>
				        </div>
				    {% endfor %}
		      	</div>
		    </div>
		</div>
	</div>
{% endblock %}